ME-Model-ID: iJL1678b-ME
m-model-path: iJL1678b-ME/building_data/m_model_modified.json
genbank-path: iJL1678b-ME/building_data/genome_modified.gb
df_gene_cplxs_mods_rxns: automated-org-with-refs-tRNAs.xlsx
df_TranscriptionalUnits: TUs_from_ecolime_plus_genes.txt
df_matrix_stoichiometry: reaction_matrix.txt
df_matrix_subrxn_stoich: subreaction_matrix.txt
df_metadata_orphan_rxns: orphan_and_spont_reactions.txt
df_metadata_metabolites: me_metabolites.txt
df_reaction_keff_consts: keffs-rs.txt
biocyc.genes: inputs/genes.txt
biocyc.prots: inputs/proteins.txt
biocyc.TUs: inputs/TUs.txt
biocyc.RNAs: inputs/RNAs.txt
biocyc.seqs: inputs/sequences.fasta
log_directory: iJL1678b-ME
out_directory: iJL1678b-ME
locus_tag: locus_tag
run_bbh_blast: false
dev_reference: false
add_lipoproteins: true
growth_key: mu
gam: 34.98
ngam: 1.0
complex_cofactors:
  fes_chaperones:
    CPLX0-1762: G6712-MONOMER
  bmocogdp_chaperones:
    TMAOREDUCTI-CPLX: EG12195-MONOMER
    DIMESULFREDUCT-CPLX: G6849-MONOMER
    NITRATREDUCTA-CPLX: NARJ-MONOMER
    NITRATREDUCTZ-CPLX: NARW-MONOMER
    NAP-CPLX: NAPD-MONOMER
    NAPAB-CPLX_NAPC-MONOMER: NAPD-MONOMER
  citx_subreactions:
    mod_2tpr3dpcoa_c:
    - citx_transfer_to_citd
  biotin_subreactions:
    mod_btn_c:
    - biotin_ligase
  glycyl_subreactions:
    mod_glycyl_c:
    - gre_activation
  acps_subreactions:
    mod_pan4p_c:
    - acpP_activation
  lipoate_subreactions:
    mod_lipoyl_c:
    - lipoyl_denovo_corrected
    - lipoyl_scavenging
  FeFe/NiFe:
    mod_FeFe_cofactor_c:
    - ''
    mod_NiFe_cofactor_c:
    - CPLX0-250_FORMATEDEHYDROGH-MONOMER
  fes_transfers:
  - CPLX0-7617
  - CPLX0-7824
  - IscA_tetra
START_tRNA:
- b2814
- b2815
- b2816
- b3171
lipoprotein_precursors:
  AcrA: b0463
  AcrE: b3265
  BamB: b2512
  BamC: b2477
  BamD: b2595
  BamE: b2617
  CusC: b0572
  EG10544-MONOMER: b1677
  EmtA: b1193
  LolB: b1209
  MetQ: b0197
  MltA: b2813
  MltB: b2701
  MltC: b2963
lipid_modifications:
- pg120_p
- pg141_p
- pg140_p
- pg181_p
- pg161_p
- pg160_p
- pg180_p
flux_of_biomass_constituents:
  10fthf_c: -0.000223
  2ohph_c: -0.000223
  coa_c: -0.000576
  glycogen_c: -0.14185219494685478
  mlthf_c: -0.000223
  nad_c: -0.001831
  nadp_c: -0.000447
  ribflv_c: -0.000223
  thf_c: -0.000223
  udcpdp_c: -5.5e-05
flux_of_lipid_constituents:
  pe161_p: -0.02106
  pe160_p: -0.045946
  pe160_c: -0.017868
  pe161_c: -0.054154
  kdo2lipid4_e: -0.01945
braun's_lipoproteins:
- EG10544-MONOMER
braun's_lpp_flux: -0.003597
braun's_murein_flux: -0.013894
gr_data_doublings_per_hour:
- 0
- 0.6
- 1.0
- 1.5
- 2.0
- 2.5
percent_dna_data:
- 0.0592
- 0.0512
- 0.033
- 0.0252
- 0.0222
- 0.0208
defer_to_rxn_matrix:
- NHFRBO
- ACPS11
- FMETTRS
- ATPM
selenocysteine_enzymes:
- SelA_deca_mod_pydx5p(10)
- SelB_mono
pg_pe_160:
- Lgt_MONOMER
- LspA_MONOMER
other_lipids:
- EG10168-MONOMER
rna_polymerases:
  RNAP_RpoHmono:
    sigma_factor: RpoH_mono
    polymerase: hRNAP_mod_zn2(1)_mod_mg2(2)
  RNAP_RpoSmono:
    sigma_factor: RpoS_mono
    polymerase: hRNAP_mod_zn2(1)_mod_mg2(2)
  RNAP_RpoEmono:
    sigma_factor: RpoE_mono
    polymerase: hRNAP_mod_zn2(1)_mod_mg2(2)
  RNAP_FliAmono:
    sigma_factor: FliA_mono
    polymerase: hRNAP_mod_zn2(1)_mod_mg2(2)
  RNAP_RpoNmono:
    sigma_factor: RpoN_mono
    polymerase: hRNAP_mod_zn2(1)_mod_mg2(2)
  RNAP_FecImono:
    sigma_factor: FecI_mono
    polymerase: hRNAP_mod_zn2(1)_mod_mg2(2)
  RNAP_RpoDmono:
    sigma_factor: RpoD_mono
    polymerase: hRNAP_mod_zn2(1)_mod_mg2(2)
translocation_multipliers:
  YidC_MONOMER:
    b1855: 2.0
    b3731: 2.0
  TatE_MONOMER:
    b4072: 20.0
    b1475: 5.166666666666667
    b1474: 5.166666666666667
    b2817: 22.0
    b0973: 14.0
    b0972: 14.0
    b0997: 13.5
    b3893: 15.5
    b0152: 21.0
    b3894: 15.5
    b1589: 14.0
    b1588: 15.0
    b2938: 6.25
    b1587: 14.0
    b1872: 26.0
    b2997: 14.0
    b2996: 21.0
    b2994: 14.0
    b2435: 20.0
    b0894: 26.0
    b0123: 23.0
    b2206: 27.0
    b2205: 20.0
  TatA_MONOMER:
    b4072: 20.0
    b1475: 5.166666666666667
    b1474: 5.166666666666667
    b2817: 22.0
    b0973: 14.0
    b0972: 14.0
    b0997: 13.5
    b3893: 15.5
    b0152: 21.0
    b3894: 15.5
    b1589: 14.0
    b1588: 15.0
    b2938: 6.25
    b1587: 14.0
    b1872: 26.0
    b2997: 14.0
    b2996: 21.0
    b2994: 14.0
    b2435: 20.0
    b0894: 26.0
    b0123: 23.0
    b2206: 27.0
    b2205: 20.0
amino_acid_trna_synthetase:
  ala__L_c: Ala_RS_tetra_mod_zn2(4)
  arg__L_c: ArgS_mono_mod_mg2(1)
  asn__L_c: Asn_RS_dim
  asp__L_c: Asp_RS_dim
  cys__L_c: CysS_mono_mod_zn2(1)
  gln__L_c: GlnS_mono
  glu__L_c: GltX_mono_mod_mg2(1)_mod_zn2(1)
  gly_c: Gly_RS_tetra
  his__L_c: His_RS_dim_mod_mg2(4)
  ile__L_c: IleS_mono_mod_zn2(2)
  leu__L_c: LeuS_mono
  lys__L_c: generic_lys_ligase
  met__L_c: Met_RS_dim_mod_zn2(2)
  phe__L_c: Phe_RS_tetra_mod_mg2(1)
  pro__L_c: Pro_RS_dim
  ser__L_c: Ser_RS_dim_mod_mg2(1)
  thr__L_c: Thr_RS_dim_mod_zn2(1)
  trp__L_c: Trp_RS_dim_mod_mg2(1)
  tyr__L_c: Tyr_RS_dim
  val__L_c: ValS_mono_mod_mg2(1)
peptide_release_factors:
  UAA: generic_RF
  UAG: PrfA_mono
  UGA: PrfB_mono
